### ISSUE TITLE
How to implement

### ISSUE THREAD

**Issue by brett18618** [brianjimenez/pygso#1]
Hi, thanks for your work first. Can you provide an example of calling the methods or functions of it?

**Comment by brianjimenez** [comment]
Hi, I apologize for the lack of documentation. I started the project longtime ago and I didn't finish it properly, but you can find an example in the same `test` folder: https://github.com/brianjimenez/pygso/blob/master/test/test_gso.py.

**Comment by Nikhitha74** [comment]
Hi,  thanks for posting your work. I am trying to utilise the code provided by you for optimisation purpose. But i get an error in Parameters.py and Coordinates. py where there is a try block . it is showing error in the line except Exception, e in these two files. should i create a coordinates and config file. kindly provide me a feedback

**Comment by brianjimenez** [comment]
Hi @Nikhitha74 , did you try to run test_gso.py? If you share how you're trying to use the library I can have a quick look.
